### ISSUE TITLE
join error

### ISSUE THREAD

**Issue by Dmitri233** [Josewowgame2888/SkyWars-Nukkit#2]
An error is prompted each time you join the game.
May be spam

```
2019-06-29 19:46:07.247 [main] FATAL - Could not pass event "cn.nukkit.event.player.PlayerInteractEvent" to "SkyWars v1.0": null on nl.sw.jose.main.Arenas
2019-06-29 19:46:07.249 [main] ERROR - Throwing
cn.nukkit.utils.EventException: null
	at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:34) ~[server.jar:?]
	at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:56) ~[server.jar:?]
	at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:546) [server.jar:?]
	at cn.nukkit.block.BlockPressurePlateBase.onEntityCollide(BlockPressurePlateBase.java:129) [server.jar:?]
	at cn.nukkit.Player.checkBlockCollision(Player.java:1392) [server.jar:?]
	at cn.nukkit.entity.Entity.entityBaseTick(Entity.java:1209) [server.jar:?]
	at cn.nukkit.entity.EntityLiving.entityBaseTick(EntityLiving.java:209) [server.jar:?]
	at cn.nukkit.Player.onUpdate(Player.java:1668) [server.jar:?]
	at cn.nukkit.Server.checkTickUpdates(Server.java:1041) [server.jar:?]
	at cn.nukkit.Server.tick(Server.java:1134) [server.jar:?]
	at cn.nukkit.Server.tickProcessor(Server.java:903) [server.jar:?]
	at cn.nukkit.Server.start(Server.java:880) [server.jar:?]
	at cn.nukkit.Server.<init>(Server.java:565) [server.jar:?]
	at cn.nukkit.Nukkit.main(Nukkit.java:112) [server.jar:?]
Caused by: java.lang.NullPointerException
	at nl.sw.jose.main.Arenas.PlayerInteractItems(Arenas.java:500) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor27.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
	at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:29) ~[server.jar:?]
	... 13 more
```

**Comment by Josewowgame2888** [comment]
I am working on it
